### ISSUE TITLE
Info printer output is garbled

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2249]
```
encodedName: Lhelloworld_HelloWorld$
isExported: true
kind: ModuleClass
superClass: Some(O)
interfaces: [sjs_js_JSApp]
methods:
  $$js$exported$meth$main__O:
    staticMethodsCalled:
      
    
  main__V:
    methodsCalled:
      sjs_js_Any$: [: [fromInt__I__sjs_js_Any}
      Lhelloworld_HelloWorld$: [: [useMyTrait__Lhelloworld_MyTrait__V, useParamTrait__Lhelloworld_ParamTrait__V, foo$1__p1__F1__sjs_js_Any, doWithBody$1__p1__F0__V}
    methodsCalledStatically:
      sjsr_AnonFunction0: [init___sjs_js_Function0}
      Lhelloworld_HelloWorld$$anonfun$main$2: [init___}
      sjsr_AnonFunction1: [init___sjs_js_Function1}
    instantiatedClasses: [Lhelloworld_MyJSClass, sjsr_AnonFunction1, Lhelloworld_HelloWorld$$anonfun$main$2, sjs_js_Object, sjsr_AnonFunction0]accessedModules: [sjs_js_Any$]
  useParamTrait__Lhelloworld_ParamTrait__V:
    methodsCalled:
      s_Predef$: [: [println__O__V}
    accessedModules: [s_Predef$]
  useMyTrait__Lhelloworld_MyTrait__V:
    methodsCalled:
      s_Predef$: [: [println__O__V}
    accessedModules: [s_Predef$]
  doWithBody$1__p1__F0__V:
    
  foo$1__p1__F1__sjs_js_Any:
    methodsCalled:
      F1: [: [apply__O__O}
    
  init___:
    methodsCalledStatically:
      O: [init___}
    staticMethodsCalled:
      O: [init___}
    
  main:
    isExported: true
    methodsCalled:
      Lhelloworld_HelloWorld$: [: [$$js$exported$meth$main__O}
```
